### ISSUE TITLE
adapter error when using res.reply()

### ISSUE THREAD

**Issue by reicruz** [chen-ye/hubot-fb#11]
Receiving the following error when calling calling `res.reply`

<img width="709" alt="screen shot 2016-06-16 at 10 26 48 am" src="https://cloud.githubusercontent.com/assets/4438261/16120338/22a304fe-33ad-11e6-9c29-e8410a3fa126.png">

**Comment by reicruz** [comment]
https://github.com/chen-ye/hubot-fb/blob/master/src/fb.coffee#L92

Strings is being spliced (`...`) twice.

`res.reply(envelope, strings...)` should be `res.reply(envelope, string)` since there is already a splice in `res.send`

**Comment by chen-ye** [comment]
`...` is a splat.  I believe this should be fixed with https://github.com/chen-ye/hubot-fb/commit/8fa6b3cdac48a85dd57e048279248b79220c3f9a.  can you verify? (you can switch to using a specific commit using http://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json)

**Comment by reicruz** [comment]
:+1: works as expected. ready to publish @chen-ye
