### ISSUE TITLE
Allowing access of user_id and other data with text only messages.

### ISSUE THREAD

**Issue by himvais** [chen-ye/hubot-fb#15]
While scripting common text messages, how do I get access to facebook_user_id of the sender.
It can be used to identify a returning user and change the behaviour of the bot accordingly.

**Comment by chen-ye** [comment]
apologies for the response delay! I wasn't able to work on this in the summer due to actually being at FB.  If this is still an issue, can you clarify who's user_id you want access to? A person messaging the bot? 

Their USER_ID is included in the receive api, and is persistent across sessions (but not different bots), and is /not/ mapped to their facebook_user_id (which is a facebook platform limitation). You can probably get around it by using the account linking api: https://developers.facebook.com/docs/messenger-platform/account-linking.
